import { useEffect, useState } from "react";
import { CalendarDays, MapPin, MessageCircle, Users } from "lucide-react";
import PageShell from "@/components/PageShell";
import Seo from "@/components/Seo";
import ResponsiveImage from "@/components/ResponsiveImage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { money, waterActivities, type WaterActivity } from "@/data/siteData";
import { trackAndGetThePointUrl } from "@/lib/referral";

function ActivityCard({ activity }: { activity: WaterActivity }) {
  const { lang, copy } = useLanguage(); const [option, setOption] = useState(activity.prices[0].label[lang]); const [date, setDate] = useState(""); const [people, setPeople] = useState("2");
  return <article id={activity.id} className="overflow-hidden rounded-md border border-border bg-card shadow-brand md:grid md:grid-cols-[.9fr_1.1fr]"><ResponsiveImage image={activity.image} sizes="(max-width:768px) 100vw, 42vw" alt={`${activity.title[lang]} at The Point beach, Marbella`} className="aspect-[4/3] h-full w-full object-cover" /><div className="p-5 md:p-9"><p className="mb-0 inline-flex items-center gap-2 rounded-full bg-sea px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-foam"><MapPin className="size-3" />{activity.location.name[lang]}</p><h2 className="mt-3 font-display text-4xl">{activity.title[lang]}</h2><p className="mt-3 leading-7 text-muted-foreground">{activity.description[lang]}</p><div className="mt-7 divide-y divide-border border-y border-border">{activity.prices.map((price) => <div key={price.label.en} className="flex justify-between gap-5 py-3 text-sm"><span className="text-muted-foreground">{price.label[lang]}</span><strong>{money(price.price, lang)}</strong></div>)}</div><p className="mt-3 text-xs text-muted-foreground">{copy.vatIncluded}</p><div className="mt-7 grid gap-3"><label className="text-xs font-medium">{copy.selectOption}<select className="mt-1 h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={option} onChange={(event) => setOption(event.target.value)}>{activity.prices.map((price) => <option key={price.label.en}>{price.label[lang]}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium"><CalendarDays className="mr-1 inline size-3" />{copy.fields.date}<Input type="date" min={new Date().toISOString().split("T")[0]} value={date} onChange={(event) => setDate(event.target.value)} className="mt-1" /></label><label className="text-xs font-medium"><Users className="mr-1 inline size-3" />{copy.people}<Input type="number" min="1" value={people} onChange={(event) => setPeople(event.target.value)} className="mt-1" /></label></div><Button asChild><a href="https://wa.me/34622264991" target="_blank" rel="noreferrer" onClick={(event) => { event.currentTarget.href = trackAndGetThePointUrl(lang, `${activity.title[lang]} (${option})`, people, date); }}><MessageCircle className="size-4" />{ {en:"Book with The Point on WhatsApp",es:"Reservar con The Point por WhatsApp",fr:"Réserver avec The Point sur WhatsApp"}[lang] }</a></Button></div></div></article>;
}

function FlyerSlot() {
  const { lang } = useLanguage();
  // Partner flyer slot: shown only once /media/the-point-flyer.jpg exists.
  const src = "/media/the-point-flyer.jpg"; const [ok, setOk] = useState(false);
  useEffect(() => { const img = new Image(); img.onload = () => setOk(true); img.src = src; }, []);
  if (!ok) return null;
  const title = { en: "The Point beach · full price list", es: "The Point beach · lista de precios completa", fr: "The Point beach · liste complète des prix" }[lang];
  const button = { en: "Book with The Point on WhatsApp", es: "Reservar con The Point por WhatsApp", fr: "Réserver avec The Point sur WhatsApp" }[lang];
  return <section className="pt-10 md:pt-16"><div className="mx-auto max-w-7xl px-5 md:px-10"><h2 className="mb-6 font-display text-4xl md:text-5xl">{title}</h2><a href={src} target="_blank" rel="noreferrer" aria-label={`${title} — open full size`} className="block touch-pinch-zoom"><img src={src} alt="The Point beach water activities price list" width="1080" height="768" loading="lazy" className="w-full rounded-md border border-border shadow-brand" /></a><Button asChild size="lg" className="mt-5 w-full md:w-auto"><a href={`https://wa.me/34622264991`} target="_blank" rel="noreferrer" onClick={(event) => { event.currentTarget.href = trackAndGetThePointUrl(lang, "Flyer / general enquiry", "", ""); }}><MessageCircle className="size-4" />{button}</a></Button></div></section>;
}

export default function ActivitiesPage() { const { lang, copy } = useLanguage(); return <PageShell><Seo lang={lang} page="activities" path="/activities" /><section className="bg-primary pb-16 pt-32 text-primary-foreground md:pb-20 md:pt-40"><div className="mx-auto max-w-7xl px-5 md:px-10"><p className="section-kicker">The Point beach · Marbella</p><h1 className="max-w-4xl font-display text-5xl md:text-7xl">{copy.activitiesTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">{copy.activitiesIntro}</p></div></section><FlyerSlot /><section className="py-16 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-5 md:px-10">{waterActivities.map((activity) => <ActivityCard key={activity.id} activity={activity} />)}</div></section></PageShell>; }