import { useState } from "react";
import { CalendarDays, MapPin, MessageCircle, Users } from "lucide-react";
import PageShell from "@/components/PageShell";
import Seo from "@/components/Seo";
import ResponsiveImage from "@/components/ResponsiveImage";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useLanguage } from "@/contexts/LanguageContext";
import { money, waterActivities, type WaterActivity } from "@/data/siteData";
import { getWhatsAppUrl } from "@/lib/whatsapp";

function ActivityCard({ activity }: { activity: WaterActivity }) {
  const { lang, copy } = useLanguage(); const [option, setOption] = useState(activity.prices[0].label[lang]); const [date, setDate] = useState(""); const [people, setPeople] = useState("2");
  const message = { en: `Hi Banús Charters, I would like to book ${activity.title.en}: ${option}, on ${date || "—"}, for ${people} people. Location: The Point beach, Marbella. Please confirm availability.`, es: `Hola Banús Charters, quiero reservar ${activity.title.es}: ${option}, el ${date || "—"}, para ${people} personas. Ubicación: The Point beach, Marbella. ¿Podéis confirmar disponibilidad?`, fr: `Bonjour Banús Charters, je souhaite réserver ${activity.title.fr} : ${option}, le ${date || "—"}, pour ${people} personnes. Lieu : The Point beach, Marbella. Pouvez-vous confirmer la disponibilité ?` }[lang];
  return <article id={activity.id} className="overflow-hidden rounded-md border border-border bg-card shadow-brand md:grid md:grid-cols-[.9fr_1.1fr]"><ResponsiveImage image={activity.image} sizes="(min-width:768px) 42vw, 100vw" alt={`${activity.title[lang]} at The Point beach, Marbella`} className="aspect-[4/3] h-full w-full object-cover" /><div className="p-6 md:p-9"><p className="section-kicker mb-0 flex items-center gap-2"><MapPin className="size-3" />{activity.location.name[lang]}</p><h2 className="mt-3 font-display text-4xl">{activity.title[lang]}</h2><p className="mt-3 leading-7 text-muted-foreground">{activity.description[lang]}</p><div className="mt-7 divide-y divide-border border-y border-border">{activity.prices.map((price) => <div key={price.label.en} className="flex justify-between gap-5 py-3 text-sm"><span className="text-muted-foreground">{price.label[lang]}</span><strong>{money(price.price, lang)}</strong></div>)}</div><p className="mt-3 text-xs text-muted-foreground">{copy.vatIncluded}</p><div className="mt-7 grid gap-3"><label className="text-xs font-medium">{copy.selectOption}<select className="mt-1 h-10 w-full rounded-sm border border-input bg-background px-3 text-sm" value={option} onChange={(event) => setOption(event.target.value)}>{activity.prices.map((price) => <option key={price.label.en}>{price.label[lang]}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium"><CalendarDays className="mr-1 inline size-3" />{copy.fields.date}<Input type="date" min={new Date().toISOString().split("T")[0]} value={date} onChange={(event) => setDate(event.target.value)} className="mt-1" /></label><label className="text-xs font-medium"><Users className="mr-1 inline size-3" />{copy.people}<Input type="number" min="1" value={people} onChange={(event) => setPeople(event.target.value)} className="mt-1" /></label></div><Button asChild><a href={getWhatsAppUrl(lang, message)} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />{copy.bookWhatsapp}</a></Button></div></div></article>;
}

export default function ActivitiesPage() { const { lang, copy } = useLanguage(); return <PageShell><Seo lang={lang} page="activities" path="/activities" /><section className="bg-primary pb-20 pt-40 text-primary-foreground"><div className="mx-auto max-w-7xl px-6 md:px-10"><p className="section-kicker">The Point beach · Marbella</p><h1 className="max-w-4xl font-display text-5xl md:text-7xl">{copy.activitiesTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/75">{copy.activitiesIntro}</p></div></section><section className="py-20 md:py-28"><div className="mx-auto grid max-w-7xl gap-10 px-6 md:px-10">{waterActivities.map((activity) => <ActivityCard key={activity.id} activity={activity} />)}</div></section></PageShell>; }