import { useMemo } from "react";
import { MessageCircle, SlidersHorizontal } from "lucide-react";
import { useSearchParams } from "react-router-dom";
import PageShell from "@/components/PageShell";
import FleetGrid, { priceForDuration } from "@/components/FleetGrid";
import Seo from "@/components/Seo";
import { useLanguage } from "@/contexts/LanguageContext";
import { boats } from "@/data/siteData";
import ResponsiveImage from "@/components/ResponsiveImage";
import { Button } from "@/components/ui/button";
import { getWhatsAppUrl } from "@/lib/whatsapp";

const text = {
 en: { refine: "Refine your charter", guests: "Guests", budget: "Budget", duration: "Duration", departure: "Departure", type: "Type", sort: "Sort", any: "Any", banus: "Puerto Banús", centre: "Marbella centre", catamaran: "Catamaran", yacht: "Yacht", sport: "Sport boat", low: "Price: low to high", high: "Price: high to low", capHigh: "Capacity: most guests", capLow: "Capacity: fewest guests", hidden: "boats hidden — too small for", no: "No boat matches", tell: "Tell us what you need on WhatsApp", date: "Date" },
 es: { refine: "Define tu charter", guests: "Personas", budget: "Presupuesto", duration: "Duración", departure: "Salida", type: "Tipo", sort: "Ordenar", any: "Cualquiera", banus: "Puerto Banús", centre: "Marbella centro", catamaran: "Catamarán", yacht: "Yate", sport: "Barco deportivo", low: "Precio: menor a mayor", high: "Precio: mayor a menor", capHigh: "Capacidad: más personas", capLow: "Capacidad: menos personas", hidden: "barcos ocultos — demasiado pequeños para", no: "Ningún barco coincide", tell: "Cuéntanos qué necesitas por WhatsApp", date: "Fecha" },
 fr: { refine: "Affinez votre charter", guests: "Personnes", budget: "Budget", duration: "Durée", departure: "Départ", type: "Type", sort: "Trier", any: "Tous", banus: "Puerto Banús", centre: "Centre de Marbella", catamaran: "Catamaran", yacht: "Yacht", sport: "Bateau sportif", low: "Prix : croissant", high: "Prix : décroissant", capHigh: "Capacité : plus grande", capLow: "Capacité : plus petite", hidden: "bateaux masqués — trop petits pour", no: "Aucun bateau ne correspond", tell: "Dites-nous ce qu’il vous faut sur WhatsApp", date: "Date" },
} as const;
const capacity = (value: string) => Number.parseInt(value, 10);
const budgetMatches = (price: number | undefined, budget: string) => { if (!price || budget === "any") return true; if (budget === "0-500") return price <= 500; if (budget === "500-1000") return price >= 500 && price <= 1000; if (budget === "1000-2000") return price >= 1000 && price <= 2000; return price >= 2000; };
const typeOf = (slug: string) => slug.includes("catamaran") ? "catamaran" : slug.includes("rinker") || slug.includes("saxdor") ? "sport" : "yacht";

export default function FleetPage() {
 const { lang, copy } = useLanguage(); const t = text[lang]; const [params, setParams] = useSearchParams();
 const guests = Math.max(1, Math.min(12, Number(params.get("guests")) || 2)); const budget = params.get("budget") || "any"; const duration = Number(params.get("duration")) || 2; const departure = params.get("departure") || "any"; const type = params.get("type") || "any"; const sort = params.get("sort") || "low"; const date = params.get("date") || "";
 const update = (key: string, value: string) => { const next = new URLSearchParams(params); next.set(key, value); setParams(next, { replace: true }); };
 const { visible, hiddenCount } = useMemo(() => { const hiddenCount = boats.filter((boat) => capacity(boat.capacity) < guests).length; const filtered = boats.filter((boat) => { const price = priceForDuration(boat, duration); return capacity(boat.capacity) >= guests && (departure === "any" || boat.location.id === departure) && (type === "any" || typeOf(boat.slug) === type) && budgetMatches(price, budget) && (boat.priceOnRequest || price !== undefined); }); return { hiddenCount, visible: filtered.sort((a,b) => { if (sort === "cap-high") return capacity(b.capacity)-capacity(a.capacity); if (sort === "cap-low") return capacity(a.capacity)-capacity(b.capacity); const ap=priceForDuration(a,duration), bp=priceForDuration(b,duration); if (ap === undefined) return 1; if (bp === undefined) return -1; return sort === "high" ? bp-ap : ap-bp; }) }; }, [guests,budget,duration,departure,type,sort]);
 const waMessage = { en: `Hi Banús Charters, I need a boat for ${guests} guests, ${duration} hours, budget ${budget}, departure ${departure}${date ? ` on ${date}` : ""}.`, es: `Hola Banús Charters, necesito un barco para ${guests} personas, ${duration} horas, presupuesto ${budget}, salida ${departure}${date ? ` el ${date}` : ""}.`, fr: `Bonjour Banús Charters, je cherche un bateau pour ${guests} personnes, ${duration} heures, budget ${budget}, départ ${departure}${date ? ` le ${date}` : ""}.` }[lang];
 return <PageShell><Seo lang={lang} page="fleet" path="/fleet" /><section className="page-hero min-h-[50vh]"><ResponsiveImage image={boats[0].images[0]} sizes="100vw" loading="eager" alt="Banús Charters catamaran in Marbella" /><div className="page-hero-overlay" /><div className="page-hero-content"><p className="section-kicker">Puerto Banús · Marbella Centre</p><h1>{copy.nav.fleet}</h1><p>{copy.fleetText}</p></div></section>
 <section className="sticky top-20 z-30 border-b border-border bg-background/95 py-4 backdrop-blur"><div className="mx-auto max-w-7xl px-4 md:px-10"><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.15em]"><SlidersHorizontal className="size-4 text-accent"/>{t.refine}</div><div className="filter-scroll"><label>{t.guests}<input type="number" min="1" max="12" value={guests} onChange={(e)=>update("guests",e.target.value)}/></label><label>{t.budget}<select value={budget} onChange={(e)=>update("budget",e.target.value)}><option value="any">{t.any}</option><option value="0-500">≤ €500</option><option value="500-1000">€500–1,000</option><option value="1000-2000">€1,000–2,000</option><option value="2000+">€2,000+</option></select></label><label>{t.duration}<select value={duration} onChange={(e)=>update("duration",e.target.value)}>{[1,2,3,4,6,8].map(h=><option key={h} value={h}>{h} h</option>)}</select></label><label>{t.departure}<select value={departure} onChange={(e)=>update("departure",e.target.value)}><option value="any">{t.any}</option><option value="puerto-banus">{t.banus}</option><option value="marbella-centre">{t.centre}</option></select></label><label>{t.type}<select value={type} onChange={(e)=>update("type",e.target.value)}><option value="any">{t.any}</option><option value="catamaran">{t.catamaran}</option><option value="yacht">{t.yacht}</option><option value="sport">{t.sport}</option></select></label><label>{t.date}<input type="date" value={date} min={new Date().toISOString().split("T")[0]} onChange={(e)=>update("date",e.target.value)}/></label><label>{t.sort}<select value={sort} onChange={(e)=>update("sort",e.target.value)}><option value="low">{t.low}</option><option value="high">{t.high}</option><option value="cap-high">{t.capHigh}</option><option value="cap-low">{t.capLow}</option></select></label></div></div></section>
 <section className="py-16 md:py-24"><div className="mx-auto max-w-7xl px-6 md:px-10">{hiddenCount > 0 && <p className="mb-8 text-sm text-muted-foreground">{hiddenCount} {t.hidden} {guests} {t.guests.toLowerCase()}.</p>}{visible.length ? <FleetGrid items={visible} selection={{ guests, duration, date }} /> : <div className="border-y border-border py-24 text-center"><h2 className="font-display text-5xl">{t.no}</h2><p className="mt-4 text-muted-foreground">{t.tell}</p><Button asChild size="lg" className="mt-8"><a href={getWhatsAppUrl(lang,waMessage)} target="_blank" rel="noreferrer"><MessageCircle/>{copy.bookWhatsapp}</a></Button></div>}</div></section></PageShell>;
}
