import { Link } from "react-router-dom";
import { ArrowRight, Check, MessageCircle, Star } from "lucide-react";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import PageShell from "@/components/PageShell";
import FleetGrid from "@/components/FleetGrid";
import Seo from "@/components/Seo";
import { useLanguage } from "@/contexts/LanguageContext";
import { getWhatsAppUrl } from "@/lib/whatsapp";
import { experiences } from "@/data/content";
import heroPoster from "@/assets/hero-coast.jpg";
import galleryDolphins from "@/assets/gallery_dolphins.jpg";
import gallery3 from "@/assets/gallery3.jpg";
import gallery4 from "@/assets/gallery4.jpg";
import gallery5 from "@/assets/gallery5.jpg";
import ctaBg from "@/assets/cta-bg.jpg";

const media = [galleryDolphins, gallery3, gallery4, gallery5];

export default function HomePage() {
  const { lang, copy } = useLanguage();
  const localBusiness = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "Banús Charters", description: "Private yacht charters in Puerto Banús, Marbella", url: `https://sea-dreams-maker.lovable.app/${lang}`, telephone: "+34600746712", address: { "@type": "PostalAddress", addressLocality: "Puerto Banús", addressRegion: "Málaga", addressCountry: "ES" }, areaServed: "Marbella" };
  return <PageShell><Seo lang={lang} jsonLd={localBusiness} />
    <section className="relative flex min-h-[92svh] items-end overflow-hidden pb-20 pt-32 md:min-h-screen md:pb-24">
      <video className="absolute inset-0 h-full w-full object-cover" autoPlay muted loop playsInline preload="metadata" poster={heroPoster} aria-label="Private yacht cruising from Puerto Banús"><source src="/videos/gallery_video1.mp4" type="video/mp4" /></video><div className="absolute inset-0 bg-hero-overlay" />
      <div className="relative mx-auto w-full max-w-7xl px-6 md:px-10"><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .9 }} className="max-w-4xl"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.2em] text-accent">Private yacht charters · Marbella</p><h1 className="max-w-4xl font-display text-5xl font-medium leading-[.98] text-primary-foreground sm:text-6xl md:text-8xl">{copy.heroTitle}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-primary-foreground/78 md:text-lg">{copy.heroText}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 rounded-sm px-7"><Link to={`/${lang}/fleet`}>{copy.viewFleet}<ArrowRight /></Link></Button><Button asChild variant="outline" size="lg" className="h-12 rounded-sm border-primary-foreground/50 bg-primary-foreground/5 px-7 text-primary-foreground hover:bg-primary-foreground hover:text-primary"><a href={getWhatsAppUrl(lang)} target="_blank" rel="noreferrer"><MessageCircle />{copy.bookWhatsapp}</a></Button></div></motion.div></div>
    </section>
    <section className="border-b border-border bg-primary py-5 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-3 px-6 sm:grid-cols-2 lg:grid-cols-4 md:px-10">{copy.trust.map((item) => <p key={item} className="flex items-center gap-2 text-xs text-primary-foreground/75"><Check className="size-3.5 text-accent" />{item}</p>)}</div></section>
    <section className="py-24 md:py-32"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="mb-14 max-w-2xl"><p className="section-kicker">{copy.fleetEyebrow}</p><h2 className="section-title">{copy.fleetTitle}</h2><p className="section-copy">{copy.fleetText}</p></div><FleetGrid /><div className="mt-12 text-center"><Button asChild variant="outline"><Link to={`/${lang}/fleet`}>{copy.viewFleet}<ArrowRight /></Link></Button></div></div></section>
    <section className="bg-primary py-24 text-primary-foreground md:py-32"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="mb-14 max-w-2xl"><p className="section-kicker">Banús, your way</p><h2 className="section-title text-primary-foreground">{copy.expTitle}</h2><p className="section-copy text-primary-foreground/65">{copy.expText}</p></div><div className="grid gap-px overflow-hidden rounded-sm border border-primary-foreground/10 bg-primary-foreground/10 md:grid-cols-2 lg:grid-cols-5">{experiences.map((exp) => <Link key={exp.id} to={`/${lang}/experiences#${exp.id}`} className="group min-h-56 bg-primary p-6 transition-colors hover:bg-primary-foreground/5"><p className="text-xs uppercase tracking-[0.16em] text-accent">0{experiences.indexOf(exp) + 1}</p><h3 className="mt-12 font-display text-2xl">{exp.title[lang]}</h3><p className="mt-3 text-sm leading-6 text-primary-foreground/60">{exp.text[lang]}</p></Link>)}</div></div></section>
    <section className="py-24 md:py-32"><div className="mx-auto max-w-7xl px-6 md:px-10"><h2 className="section-title max-w-2xl">{copy.howTitle}</h2><div className="mt-14 grid gap-10 md:grid-cols-3">{copy.how.map(([num, title, text]) => <div key={num} className="border-t border-accent pt-6"><span className="font-display text-4xl text-accent">{num}</span><h3 className="mt-5 font-display text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section>
    <section className="bg-muted py-24 md:py-32"><div className="mx-auto max-w-7xl px-6 md:px-10"><h2 className="section-title mb-12">{copy.galleryTitle}</h2><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{media.map((src, i) => <img key={src} src={src} alt={`Banús Charters yacht experience in Marbella ${i + 1}`} loading="lazy" className={`h-full min-h-52 w-full rounded-sm object-cover ${i === 0 ? "col-span-2 row-span-2" : ""}`} />)}</div></div></section>
    <section className="py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-6 md:grid-cols-2 md:px-10"><div><p className="section-kicker">FAQ</p><h2 className="section-title">{copy.faqTitle}</h2></div><Accordion type="single" collapsible>{copy.faq.slice(0, 5).map(([q, a], i) => <AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger className="text-left font-display text-xl font-normal hover:no-underline">{q}</AccordionTrigger><AccordionContent className="leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="border-y border-border py-20"><div className="mx-auto flex max-w-5xl flex-col items-center px-6 text-center"><Star className="size-7 text-accent" /><h2 className="mt-5 font-display text-3xl md:text-4xl">{copy.reviewsTitle}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{copy.reviewsText}</p><span className="mt-6 text-xs uppercase tracking-[0.14em] text-muted-foreground">{copy.reviewsLink}</span></div></section>
    <section className="relative overflow-hidden py-28 md:py-36"><img src={ctaBg} alt="Luxury yacht off the coast of Marbella" className="absolute inset-0 h-full w-full object-cover" loading="lazy" /><div className="absolute inset-0 bg-hero-overlay" /><div className="relative mx-auto max-w-4xl px-6 text-center"><h2 className="font-display text-4xl text-primary-foreground md:text-6xl">{copy.finalTitle}</h2><p className="mx-auto mt-5 max-w-2xl text-primary-foreground/70">{copy.finalText}</p><Button asChild size="lg" className="mt-8"><a href={getWhatsAppUrl(lang)} target="_blank" rel="noreferrer"><MessageCircle />{copy.bookWhatsapp}</a></Button></div></section>
  </PageShell>;
}