import { Link } from "react-router-dom";
import { ArrowRight, Check, MessageCircle, Star, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import PageShell from "@/components/PageShell";
import FleetGrid from "@/components/FleetGrid";
import Seo from "@/components/Seo";
import { useLanguage } from "@/contexts/LanguageContext";
import { getWhatsAppUrl } from "@/lib/whatsapp";
import { experiences } from "@/data/content";
import { boats, siteImages, siteVideos } from "@/data/siteData";
import ResponsiveImage from "@/components/ResponsiveImage";
import CharterFinder from "@/components/CharterFinder";
import CoastMap from "@/components/CoastMap";
import Reveal from "@/components/Reveal";
import InViewVideo from "@/components/InViewVideo";

const homeText = {
  en: { eyebrow: "Private charters · Marbella", live: "Live from Marbella · La Concha behind us", groups: "Choose by group size", groupText: "Start with the people. We’ll show you the boats that fit.", small: "Couples & small groups", medium: "Friends & families", large: "Big groups", featured: "The Marbella fleet", featuredText: "A considered collection for unhurried days, golden hours and celebrations at sea.", departures: "Three departure points", water: "More ways to meet the Mediterranean", seeActivities: "Explore water activities" },
  es: { eyebrow: "Charters privados · Marbella", live: "En directo desde Marbella · La Concha detrás", groups: "Elige por tamaño de grupo", groupText: "Empieza por las personas. Te mostraremos los barcos que encajan.", small: "Parejas y grupos pequeños", medium: "Amigos y familias", large: "Grupos grandes", featured: "La flota de Marbella", featuredText: "Una colección cuidada para días sin prisa, atardeceres y celebraciones en el mar.", departures: "Tres puntos de salida", water: "Más formas de vivir el Mediterráneo", seeActivities: "Explorar actividades acuáticas" },
  fr: { eyebrow: "Charters privés · Marbella", live: "En direct de Marbella · La Concha derrière nous", groups: "Choisissez selon votre groupe", groupText: "Commencez par les personnes. Nous vous montrons les bateaux adaptés.", small: "Couples et petits groupes", medium: "Amis et familles", large: "Grands groupes", featured: "La flotte de Marbella", featuredText: "Une collection choisie pour les journées sans hâte, les couchers de soleil et les fêtes en mer.", departures: "Trois points de départ", water: "D’autres façons de vivre la Méditerranée", seeActivities: "Explorer les activités nautiques" },
} as const;

export default function HomePage() {
  const { lang, copy } = useLanguage(); const t = homeText[lang];
  const localBusiness = { "@context": "https://schema.org", "@type": "LocalBusiness", name: "Banús Charters", description: "Private yacht charters and water activities in Marbella", url: `https://sea-dreams-maker.lovable.app/${lang}`, telephone: "+34600746712", address: { "@type": "PostalAddress", addressLocality: "Marbella", addressRegion: "Málaga", addressCountry: "ES" }, areaServed: [{ "@type": "Place", name: "Puerto Banús" }, { "@type": "Place", name: "Marbella Centre", containsPlace: [{ "@type": "Place", name: "Puerto Deportivo de Marbella" }, { "@type": "Place", name: "The Point beach, Marbella" }] }] };
  const groups = [{ title: t.small, range: "2–6", guests: 4, image: boats[5].images[0] }, { title: t.medium, range: "7–10", guests: 8, image: boats[1].images[0] }, { title: t.large, range: "11–12", guests: 12, image: boats[0].images[0] }];
  return <PageShell><Seo lang={lang} jsonLd={localBusiness} />
    <section className="home-hero"><div className="hero-video-frame"><video className="h-full w-full object-cover" autoPlay muted loop playsInline preload="metadata" poster={siteVideos.hero.poster.src} aria-label="Banús Charters catamaran with La Concha mountain in Marbella"><source src={siteVideos.hero.src} type="video/mp4" /></video><p>{t.live}</p></div><div className="hero-mobile-overlay" /><div className="hero-grain" />
      <div className="hero-content"><div className="animate-fade-in"><p className="section-kicker text-accent">{t.eyebrow}</p><h1 className="font-display text-6xl font-medium leading-[.86] text-primary-foreground sm:text-7xl lg:text-8xl xl:text-9xl">{copy.heroTitle}</h1><p className="mt-6 max-w-xl text-base leading-7 text-primary-foreground/85 md:text-lg">{copy.heroText}</p><div className="mt-10"><CharterFinder /></div></div></div>
    </section>
    <section className="border-b border-primary-foreground/10 bg-primary py-6 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-4 px-6 sm:grid-cols-2 lg:grid-cols-4 md:px-10">{copy.trust.map((item) => <p key={item} className="flex items-center gap-3 text-xs text-primary-foreground/75"><Check className="size-4 text-accent" />{item}</p>)}</div></section>
    <Reveal><section className="py-24 md:py-36"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="max-w-3xl"><p className="section-kicker">01 · Curated by capacity</p><h2 className="section-title">{t.groups}</h2><p className="section-copy">{t.groupText}</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{groups.map((group) => <Link key={group.range} to={`/${lang}/fleet?guests=${group.guests}&budget=any&duration=2&departure=any`} className="editorial-tile group"><ResponsiveImage image={group.image} alt={`${group.title} yacht charter in Marbella`} sizes="(min-width:1024px) 33vw, 100vw" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-primary/90 via-primary/10 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 text-primary-foreground"><span className="text-xs uppercase tracking-[.18em] text-accent"><Users className="mr-2 inline size-4"/>{group.range}</span><h3 className="mt-3 font-display text-3xl">{group.title}</h3><ArrowRight className="mt-5 size-5 transition-transform group-hover:translate-x-2"/></div></Link>)}</div></div></section></Reveal>
    <Reveal><section className="border-y border-border bg-card py-24 md:py-36"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="flex items-end justify-between gap-8"><div className="max-w-3xl"><p className="section-kicker">02 · {copy.fleetEyebrow}</p><h2 className="section-title">{t.featured}</h2><p className="section-copy">{t.featuredText}</p></div><Button asChild variant="outline" className="hidden md:inline-flex"><Link to={`/${lang}/fleet`}>{copy.viewFleet}<ArrowRight /></Link></Button></div><div className="fleet-scroll mt-14"><FleetGrid limit={6} horizontal /></div></div></section></Reveal>
    <CoastMap />
    <Reveal><section className="py-24 md:py-36"><div className="mx-auto max-w-7xl px-6 md:px-10"><div className="mb-14 max-w-3xl"><p className="section-kicker">04 · Marbella, your way</p><h2 className="section-title">{copy.expTitle}</h2><p className="section-copy">{copy.expText}</p></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{experiences.map((exp, index) => { const image = exp.id === "water" ? siteImages.activities["jet-ski"] : siteImages.experiences[index % siteImages.experiences.length]; return <Link key={exp.id} to={`/${lang}/${exp.id === "water" ? "activities" : `experiences#${exp.id}`}`} className="experience-tile group">{exp.id === "dolphins" ? <InViewVideo src={siteVideos.dolphins.src} poster={siteVideos.dolphins.poster.src} aria-label={exp.title[lang]} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /> : <ResponsiveImage image={image} alt={`${exp.title[lang]} in Marbella`} sizes="(min-width:1024px) 33vw, (min-width:768px) 50vw, 100vw" className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/>}<div className="absolute inset-0 bg-gradient-to-t from-primary/95 via-primary/5 to-transparent"/><div className="absolute inset-x-0 bottom-0 translate-y-8 p-6 text-primary-foreground transition duration-500 group-hover:translate-y-0"><span className="text-xs text-accent">0{index + 1}</span><h3 className="mt-3 font-display text-2xl">{exp.title[lang]}</h3><p className="mt-3 line-clamp-3 text-xs leading-5 text-primary-foreground/70 opacity-0 transition group-hover:opacity-100">{exp.text[lang]}</p></div></Link>})}</div></div></section></Reveal>
    <Reveal><section className="bg-muted py-24 md:py-36"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 lg:grid-cols-[1.15fr_.85fr] md:px-10"><div className="relative"><ResponsiveImage image={siteImages.activities["jet-ski"]} sizes="(min-width:1024px) 58vw, 100vw" alt="Jet Ski at The Point beach in Marbella" className="aspect-[16/10] w-full object-cover"/><div className="absolute -bottom-6 right-6 border border-accent/40 bg-primary px-6 py-4 text-primary-foreground"><span className="text-xs uppercase tracking-[.18em] text-accent">The Point</span><p className="font-display text-2xl">Marbella centre</p></div></div><div><p className="section-kicker">05 · The Point beach</p><h2 className="section-title">{t.water}</h2><p className="section-copy">{copy.activitiesIntro}</p><Button asChild className="mt-8"><Link to={`/${lang}/activities`}>{t.seeActivities}<ArrowRight /></Link></Button></div></div></section></Reveal>
    <Reveal><section className="py-24 md:py-36"><div className="mx-auto max-w-7xl px-6 md:px-10"><h2 className="section-title max-w-2xl">{copy.howTitle}</h2><div className="mt-16 grid gap-10 md:grid-cols-3">{copy.how.map(([num, title, text]) => <div key={num} className="border-t border-accent pt-7"><span className="font-display text-5xl text-accent">{num}</span><h3 className="mt-7 font-display text-3xl">{title}</h3><p className="mt-4 max-w-sm text-sm leading-7 text-muted-foreground">{text}</p></div>)}</div></div></section></Reveal>
    <section className="border-y border-border bg-card py-24 md:py-32"><div className="mx-auto grid max-w-7xl gap-14 px-6 md:grid-cols-[.7fr_1.3fr] md:px-10"><div><p className="section-kicker">FAQ</p><h2 className="section-title">{copy.faqTitle}</h2></div><Accordion type="single" collapsible>{copy.faq.slice(0, 6).map(([q, a], i) => <AccordionItem key={q} value={`faq-${i}`}><AccordionTrigger className="text-left font-display text-2xl font-normal hover:no-underline">{q}</AccordionTrigger><AccordionContent className="max-w-xl leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section>
    <section className="border-y border-border py-20"><div className="mx-auto flex max-w-5xl flex-col items-center px-6 text-center"><Star className="size-7 text-accent" /><h2 className="mt-5 font-display text-4xl">{copy.reviewsTitle}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-muted-foreground">{copy.reviewsText}</p><span className="mt-6 text-xs uppercase tracking-[0.14em] text-muted-foreground">{copy.reviewsLink}</span></div></section>
    <section className="relative min-h-[70vh] overflow-hidden py-28 md:py-40"><ResponsiveImage image={siteImages.cta} sizes="100vw" alt="Azimut yacht charter in Marbella" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-hero-overlay" /><div className="relative mx-auto max-w-5xl px-6 text-center"><p className="section-kicker">Banús Charters</p><h2 className="font-display text-5xl leading-none text-primary-foreground md:text-8xl">{copy.finalTitle}</h2><p className="mx-auto mt-7 max-w-2xl text-primary-foreground/75">{copy.finalText}</p><Button asChild size="lg" className="mt-10 h-14 px-8"><a href={getWhatsAppUrl(lang)} target="_blank" rel="noreferrer"><MessageCircle />{copy.bookWhatsapp}</a></Button></div></section>
  </PageShell>;
}
