import { MessageCircle, MapPin } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Button } from "@/components/ui/button";
import PageShell from "@/components/PageShell";
import Seo from "@/components/Seo";
import { useLanguage } from "@/contexts/LanguageContext";
import { getWhatsAppUrl } from "@/lib/whatsapp";
import { locations, siteImages } from "@/data/siteData";
import ResponsiveImage from "@/components/ResponsiveImage";

const Head = ({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) => <section className="bg-primary pb-20 pt-40 text-primary-foreground"><div className="mx-auto max-w-7xl px-6 md:px-10"><p className="section-kicker">{eyebrow}</p><h1 className="max-w-4xl font-display text-5xl md:text-7xl">{title}</h1>{text && <p className="mt-6 max-w-2xl text-lg leading-8 text-primary-foreground/65">{text}</p>}</div></section>;

export function FaqPage() { const { lang, copy } = useLanguage(); const schema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: copy.faq.map(([q, a]) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) }; return <PageShell><Seo lang={lang} page="faq" path="/faq" jsonLd={schema} /><Head eyebrow="Banús Charters" title={copy.faqTitle} /><section className="py-20"><div className="mx-auto max-w-3xl px-6"><Accordion type="single" collapsible>{copy.faq.map(([q, a], i) => <AccordionItem key={q} value={`q-${i}`}><AccordionTrigger className="py-6 text-left font-display text-2xl font-normal hover:no-underline">{q}</AccordionTrigger><AccordionContent className="pb-7 text-base leading-7 text-muted-foreground">{a}</AccordionContent></AccordionItem>)}</Accordion></div></section></PageShell>; }

export function AboutPage() { const { lang, copy } = useLanguage(); return <PageShell><Seo lang={lang} page="about" path="/about" /><Head eyebrow="Puerto Banús · Marbella" title={copy.aboutTitle} /><section className="py-20 md:py-28"><div className="mx-auto grid max-w-7xl items-center gap-14 px-6 md:grid-cols-2 md:px-10"><ResponsiveImage image={siteImages.about} sizes="(min-width:768px) 50vw, 100vw" alt="Puerto Banús coast seen from a charter yacht" className="aspect-[4/5] w-full rounded-sm object-cover" /><div><p className="section-kicker">Banús Charters</p><p className="font-display text-3xl leading-snug md:text-4xl">{copy.aboutText}</p><div className="mt-10 border-l-2 border-accent pl-6 text-sm leading-7 text-muted-foreground">{lang === "es" ? "Actuamos como intermediarios: gestionamos la reserva y conectamos al cliente con el operador náutico autorizado que presta y asegura el servicio." : lang === "fr" ? "Nous agissons comme intermédiaire : nous gérons la réservation et vous mettons en relation avec l'opérateur nautique agréé qui assure et fournit le service." : "We act as an intermediary: we manage the booking and connect you with the licensed marine operator that provides and insures the service."}</div></div></div></section></PageShell>; }

export function ContactPage() { const { lang, copy } = useLanguage(); return <PageShell><Seo lang={lang} page="contact" path="/contact" /><Head eyebrow="WhatsApp · Puerto Banús" title={copy.contactTitle} text={copy.contactText} /><section className="py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 md:grid-cols-2 md:px-10"><div className="rounded-sm border border-border p-8"><MessageCircle className="size-6 text-accent" /><h2 className="mt-8 font-display text-3xl">WhatsApp</h2><p className="mt-3 text-sm text-muted-foreground">+34 600 74 67 12</p><Button asChild className="mt-8"><a href={getWhatsAppUrl(lang)} target="_blank" rel="noreferrer">{copy.bookWhatsapp}</a></Button></div><div className="overflow-hidden rounded-sm border border-border bg-muted"><iframe title="Puerto Banús map" src="https://www.openstreetmap.org/export/embed.html?bbox=-4.969%2C36.478%2C-4.937%2C36.496&layer=mapnik&marker=36.487%2C-4.953" className="h-[420px] w-full border-0" loading="lazy" /><div className="space-y-3 p-5 text-sm text-muted-foreground">{([locations["puerto-banus"], locations["marbella-centre"], locations["the-point"]]).map((place) => <p key={place.id} className="flex items-start gap-2"><MapPin className="mt-0.5 size-4 shrink-0 text-accent" /><span><strong className="text-foreground">{place.name[lang]}</strong><br />{place.address[lang]}</span></p>)}</div></div></div></section></PageShell>; }

type LegalKind = "legal" | "privacy" | "cookies" | "terms";
const legalContent: Record<LegalKind, Record<"en" | "es" | "fr", { title: string; sections: [string, string][] }>> = {
  legal: { en: { title: "Legal notice", sections: [["Service provider", "Banús Charters provides charter brokerage and booking coordination services from Puerto Banús, Marbella."], ["Intermediary role", "Banús Charters is not the vessel operator. The charter service is provided, crewed and insured by the licensed boat company identified in the booking confirmation."], ["Website use", "Information is provided in good faith and may change. Availability is never confirmed until accepted by the operator and the deposit is received."]] }, es: { title: "Aviso legal", sections: [["Prestador del servicio", "Banús Charters presta servicios de intermediación y gestión de reservas desde Puerto Banús, Marbella."], ["Papel de intermediario", "Banús Charters no opera las embarcaciones. El charter es prestado, tripulado y asegurado por la empresa náutica autorizada indicada en la confirmación."], ["Uso de la web", "La información se ofrece de buena fe y puede cambiar. La disponibilidad solo queda confirmada cuando la acepta el operador y se recibe el depósito."]] }, fr: { title: "Mentions légales", sections: [["Prestataire", "Banús Charters fournit des services de courtage et de coordination de réservations depuis Puerto Banús, Marbella."], ["Rôle d'intermédiaire", "Banús Charters n'exploite pas les bateaux. Le charter est fourni, assuré et encadré par la compagnie nautique agréée indiquée dans la confirmation."], ["Utilisation du site", "Les informations sont fournies de bonne foi et peuvent évoluer. La disponibilité n'est confirmée qu'après accord de l'opérateur et réception de l'acompte."]] } },
  privacy: { en: { title: "Privacy policy", sections: [["Data we collect", "When you request a booking we collect the details you submit: name, contact details, date, group size and boat interest."], ["Purpose and lawful basis", "We use this information to answer your request and take steps toward a charter booking. We do not sell your data."], ["Retention and rights", "We keep enquiries only as long as needed for booking, legal and accounting purposes. Under GDPR you may request access, correction or deletion through our published contact channel."]] }, es: { title: "Política de privacidad", sections: [["Datos que recogemos", "Al solicitar una reserva recogemos los datos que envías: nombre, contacto, fecha, grupo y barco de interés."], ["Finalidad y base legal", "Usamos esta información para responder y gestionar los pasos previos a la reserva. No vendemos tus datos."], ["Conservación y derechos", "Conservamos las consultas solo durante el tiempo necesario por motivos de reserva, legales y contables. Según el RGPD puedes solicitar acceso, rectificación o supresión por nuestro canal de contacto."]] }, fr: { title: "Politique de confidentialité", sections: [["Données collectées", "Lors d'une demande, nous recueillons les informations fournies : nom, coordonnées, date, groupe et bateau souhaité."], ["Finalité et base légale", "Nous utilisons ces informations pour répondre et préparer la réservation. Nous ne vendons pas vos données."], ["Conservation et droits", "Les demandes sont conservées uniquement le temps nécessaire aux fins de réservation, légales et comptables. Le RGPD vous permet de demander accès, rectification ou suppression via notre canal de contact."]] } },
  cookies: { en: { title: "Cookie policy", sections: [["Essential storage", "The website stores your language and cookie preference so the experience works consistently."], ["Optional analytics", "Optional analytics remain disabled unless you accept them in the cookie banner."], ["Control", "You can clear site data in your browser to reset your choice."]] }, es: { title: "Política de cookies", sections: [["Almacenamiento esencial", "La web guarda el idioma y la preferencia de cookies para funcionar de forma coherente."], ["Analíticas opcionales", "Las analíticas opcionales permanecen desactivadas salvo que las aceptes en el aviso."], ["Control", "Puedes borrar los datos del sitio en tu navegador para restablecer tu elección."]] }, fr: { title: "Politique de cookies", sections: [["Stockage essentiel", "Le site mémorise la langue et votre choix de cookies pour fonctionner correctement."], ["Analyses optionnelles", "Les analyses optionnelles restent désactivées sans votre accord dans la bannière."], ["Contrôle", "Vous pouvez effacer les données du site dans votre navigateur pour réinitialiser votre choix."]] } },
  terms: { en: { title: "Booking terms", sections: [["Booking", "A booking is confirmed after operator approval and receipt of the stated deposit. The balance is paid on board as confirmed."], ["Operator", "Banús Charters acts solely as an intermediary. The licensed boat company provides the vessel, captain, insurance and charter service."], ["Weather and cancellation", "If the captain cancels for safety or weather, you may reschedule free of charge or receive a full refund of your deposit. Other cancellation terms are disclosed before payment."], ["Guest responsibility", "Guests must follow the captain's safety instructions and provide accurate group and contact information."]] }, es: { title: "Condiciones de reserva", sections: [["Reserva", "La reserva se confirma tras la aceptación del operador y la recepción del depósito indicado. El saldo se paga a bordo según la confirmación."], ["Operador", "Banús Charters actúa únicamente como intermediario. La empresa náutica autorizada presta la embarcación, capitán, seguro y servicio de charter."], ["Clima y cancelación", "Si el capitán cancela por seguridad o clima, puedes cambiar la fecha gratis o recibir el reembolso íntegro del depósito. Las demás condiciones se comunican antes del pago."], ["Responsabilidad del cliente", "Los clientes deben seguir las instrucciones de seguridad del capitán y facilitar datos correctos del grupo y contacto."]] }, fr: { title: "Conditions de réservation", sections: [["Réservation", "La réservation est confirmée après accord de l'opérateur et réception de l'acompte. Le solde est payé à bord comme convenu."], ["Opérateur", "Banús Charters agit uniquement comme intermédiaire. La compagnie nautique agréée fournit le bateau, le capitaine, l'assurance et le service."], ["Météo et annulation", "Si le capitaine annule pour sécurité ou météo, vous pouvez reporter gratuitement ou obtenir le remboursement intégral de l'acompte. Les autres conditions sont communiquées avant paiement."], ["Responsabilité des passagers", "Les passagers doivent suivre les consignes du capitaine et fournir des informations exactes."]] } },
};

export function LegalPage({ kind }: { kind: LegalKind }) { const { lang } = useLanguage(); const content = legalContent[kind][lang]; return <PageShell><Seo lang={lang} title={`${content.title} | Banús Charters`} description={`${content.title} for Banús Charters private yacht bookings.`} path={`/${kind}`} /><Head eyebrow="Banús Charters" title={content.title} /><section className="py-20"><div className="mx-auto max-w-3xl space-y-12 px-6">{content.sections.map(([title, text]) => <article key={title}><h2 className="font-display text-3xl">{title}</h2><p className="mt-4 leading-8 text-muted-foreground">{text}</p></article>)}</div></section></PageShell>; }