import { useMemo, useState, type FormEvent } from "react";
import { useSearchParams } from "react-router-dom";
import { MessageCircle, Send } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { getWhatsAppUrl } from "@/lib/whatsapp";
import type { Boat } from "@/data/siteData";
import { useLanguage } from "@/contexts/LanguageContext";

export default function BookingBox({ boat }: { boat: Boat }) {
  const { lang, copy } = useLanguage();
  const [searchParams] = useSearchParams();
  const maxGuests = Number.parseInt(boat.capacity, 10);
  const firstDuration = boat.prices[0]?.label[lang] ?? copy.priceOnRequest;
  const selectedHours = Number(searchParams.get("duration"));
  const selectedDuration = boat.prices.find((price) => Number.parseInt(price.label.en, 10) === selectedHours)?.label[lang] ?? firstDuration;
  const [form, setForm] = useState({ date: searchParams.get("date") ?? "", duration: selectedDuration, guests: searchParams.get("guests") ?? "2", name: "", email: "", phone: "", notes: "" });
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const message = useMemo(() => ({ en: `Hi Banús Charters, my name is ${form.name || "—"}. I am interested in ${boat.name} at ${boat.location.name.en} on ${form.date || "—"}${boat.priceOnRequest ? "" : ` for ${form.duration}`}, with ${form.guests} guests. Please confirm availability${boat.priceOnRequest ? " and send me a quote" : ""}.`, es: `Hola Banús Charters, me llamo ${form.name || "—"}. Me interesa ${boat.name} en ${boat.location.name.es} el ${form.date || "—"}${boat.priceOnRequest ? "" : `, durante ${form.duration}`}, para ${form.guests} personas. ¿Podéis confirmar disponibilidad${boat.priceOnRequest ? " y enviarme un presupuesto" : ""}?`, fr: `Bonjour Banús Charters, je m'appelle ${form.name || "—"}. Je souhaite réserver ${boat.name} à ${boat.location.name.fr} le ${form.date || "—"}${boat.priceOnRequest ? "" : `, pour ${form.duration}`}, pour ${form.guests} personnes. Pouvez-vous confirmer la disponibilité${boat.priceOnRequest ? " et m'envoyer un devis" : ""} ?` }[lang]), [form, boat, lang]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setStatus("sending"); const { error } = await supabase.from("booking_requests").insert({ language: lang, source: "boat_detail", boat_slug: boat.slug, requested_date: form.date, duration: form.duration, guests: Number(form.guests), name: form.name.trim(), email: form.email.trim(), phone: form.phone.trim(), notes: form.notes.trim() || null }); setStatus(error ? "error" : "sent"); };
  if (boat.priceOnRequest) return <aside className="rounded-lg border border-border bg-card p-6 shadow-brand lg:sticky lg:top-28"><p className="section-kicker mb-0">{boat.location.name[lang]}</p><h2 className="mt-2 font-display text-3xl">{copy.reserveTitle}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.priceOnRequest} · {copy.reserveNote}</p><div className="mt-6 grid gap-4"><label className="text-xs font-medium">{copy.fields.date}<Input type="date" min={new Date().toISOString().split("T")[0]} value={form.date} onChange={(e) => set("date", e.target.value)} className="mt-1" /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium">{copy.fields.guests}<Input type="number" min="1" max={maxGuests} value={form.guests} onChange={(e) => set("guests", e.target.value)} className="mt-1" /></label><label className="text-xs font-medium">{copy.fields.name}<Input value={form.name} onChange={(e) => set("name", e.target.value)} className="mt-1" /></label></div><Button asChild><a href={getWhatsAppUrl(lang, message)} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />{copy.checkAvailability}</a></Button></div></aside>;
  return <aside className="rounded-lg border border-border bg-card p-6 shadow-brand lg:sticky lg:top-28"><p className="section-kicker mb-0">{boat.location.name[lang]}</p><h2 className="mt-2 font-display text-3xl">{copy.reserveTitle}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.reserveNote}</p><form onSubmit={submit} className="mt-6 grid gap-4"><label className="text-xs font-medium">{copy.fields.date}<Input required type="date" min={new Date().toISOString().split("T")[0]} value={form.date} onChange={(e) => set("date", e.target.value)} className="mt-1" /></label><label className="text-xs font-medium">{copy.fields.duration}<select value={form.duration} onChange={(e) => set("duration", e.target.value)} className="mt-1 h-10 w-full rounded-sm border border-input bg-background px-3 text-sm">{boat.prices.map((p, index) => <option key={p.label.en} value={p.label[lang]}>{boat.hourlyRate ? `${p.label[lang]} · €${boat.hourlyRate} × ${index + 1} = €${p.price}` : `${p.label[lang]} · €${p.price}`}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium">{copy.fields.guests}<Input required type="number" min="1" max={maxGuests} value={form.guests} onChange={(e) => set("guests", e.target.value)} className="mt-1" /></label><label className="text-xs font-medium">{copy.fields.name}<Input required value={form.name} onChange={(e) => set("name", e.target.value)} className="mt-1" /></label></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-medium">{copy.fields.email}<Input required type="email" value={form.email} onChange={(e) => set("email", e.target.value)} className="mt-1" /></label><label className="text-xs font-medium">{copy.fields.phone}<Input required type="tel" value={form.phone} onChange={(e) => set("phone", e.target.value)} className="mt-1" /></label></div><label className="text-xs font-medium">{copy.fields.notes}<Textarea value={form.notes} onChange={(e) => set("notes", e.target.value)} className="mt-1 min-h-20" /></label><Button type="submit" disabled={status === "sending"}><Send className="size-4" />{status === "sending" ? copy.sending : copy.sendRequest}</Button><Button asChild type="button" variant="outline"><a href={getWhatsAppUrl(lang, message)} target="_blank" rel="noreferrer"><MessageCircle className="size-4" />{copy.sendWhatsapp}</a></Button>{status === "sent" && <p role="status" className="text-sm text-primary">{copy.sent}</p>}{status === "error" && <p role="alert" className="text-sm text-destructive">{copy.requestError}</p>}</form></aside>;
}