import { useLanguage } from "@/contexts/LanguageContext";

const labels = {
  en: { title: "Three ways into the Mediterranean", text: "One coastline, three distinct starting points.", banus: "Private yachts & catamarans", marina: "Sport boats & cruisers", point: "Water activities", note: "On a clear day you can see Gibraltar and Africa." },
  es: { title: "Tres puertas al Mediterráneo", text: "Una costa, tres puntos de salida distintos.", banus: "Yates privados y catamaranes", marina: "Barcos deportivos y cruisers", point: "Actividades acuáticas", note: "En un día claro se ven Gibraltar y África." },
  fr: { title: "Trois accès à la Méditerranée", text: "Un littoral, trois points de départ distincts.", banus: "Yachts privés et catamarans", marina: "Bateaux sportifs et cruisers", point: "Activités nautiques", note: "Par temps clair, Gibraltar et l’Afrique sont visibles." },
} as const;

export default function CoastMap() {
  const { lang } = useLanguage(); const t = labels[lang];
  const stops = [["Puerto Banús", t.banus], ["Puerto Deportivo de Marbella", t.marina], ["The Point beach", t.point]];
  return <section className="overflow-hidden bg-primary py-16 text-primary-foreground md:py-36"><div className="mx-auto max-w-7xl px-5 md:px-10"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div><p className="section-kicker">Marbella coastline</p><h2 className="section-title max-w-full text-primary-foreground">{t.title}</h2><p className="section-copy text-primary-foreground/65">{t.text}</p><p className="mt-8 border-l border-brass pl-5 font-display text-2xl italic text-brass md:mt-10">{t.note}</p></div><ol className="relative ml-2 grid border-l border-brass/50 pl-7 md:hidden">{stops.map(([name, note], index) => <li key={name} className="relative py-5 first:pt-0 last:pb-0"><span className="absolute -left-[2.15rem] top-6 size-3 rounded-full border border-brass bg-primary first:top-1" /><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-brass">0{index + 1}</span><strong className="mt-1 block font-display text-2xl font-medium leading-tight">{name}</strong><span className="mt-2 block text-sm leading-6 text-primary-foreground/65">{note}</span></li>)}</ol><div className="relative hidden aspect-[16/9] min-h-80 md:block" aria-label="Illustrated Marbella coastline map"><svg viewBox="0 0 900 520" className="h-full w-full" role="img"><path d="M25 378 C140 330 202 387 316 332 C424 281 495 342 603 274 C686 222 760 242 875 176" fill="none" stroke="hsl(var(--brass))" strokeWidth="2"/><path d="M20 410 C180 368 230 425 350 374 C472 324 531 380 641 310 C730 256 800 280 890 214 L900 520 L0 520 Z" fill="hsl(var(--brass) / .08)"/><path d="M86 184 L190 94 L254 184 M156 184 L230 127 L298 184 M540 192 L626 79 L716 194" fill="none" stroke="hsl(var(--primary-foreground) / .16)" strokeWidth="1"/><g fill="hsl(var(--brass))">{[[185,350],[512,320],[705,260]].map(([x,y]) => <g key={x}><circle cx={x} cy={y} r="17" fill="hsl(var(--brass) / .18)"/><circle cx={x} cy={y} r="6"/></g>)}</g></svg><div className="map-label left-[6%] top-[70%]"><strong>Puerto Banús</strong><span>{t.banus}</span></div><div className="map-label left-[48%] top-[62%]"><strong>Puerto Deportivo</strong><span>{t.marina}</span></div><div className="map-label right-[2%] top-[47%]"><strong>The Point</strong><span>{t.point}</span></div></div></div></div></section>;
}
