import { Link } from "react-router-dom";
import { ArrowUpRight, Check, MapPin, Ruler, Users } from "lucide-react";
import { boats, money, type Boat } from "@/data/siteData";
import { useLanguage } from "@/contexts/LanguageContext";
import ResponsiveImage from "@/components/ResponsiveImage";
import { Button } from "@/components/ui/button";

export interface FleetSelection { guests?: number; duration?: number; date?: string }
const cardCopy = { en: { book: "Book", person: "per person", forDuration: "for", guests: "guests", swipe: "Swipe to explore" }, es: { book: "Reservar", person: "por persona", forDuration: "por", guests: "personas", swipe: "Desliza para explorar" }, fr: { book: "Réserver", person: "par personne", forDuration: "pour", guests: "personnes", swipe: "Balayez pour découvrir" } } as const;
export const priceForDuration = (boat: Boat, duration?: number) => { if (boat.priceOnRequest) return undefined; if (!duration) return boat.prices[0]?.price; return boat.prices.find((price) => Number.parseInt(price.label.en, 10) === duration)?.price; };

export default function FleetGrid({ limit, items, horizontal = false, selection }: { limit?: number; items?: Boat[]; horizontal?: boolean; selection?: FleetSelection }) {
  const { lang, copy } = useLanguage(); const t = cardCopy[lang]; const list = (items ?? boats).slice(0, limit);
  const cards = <div className={horizontal ? "fleet-carousel flex snap-x snap-mandatory gap-5" : "grid gap-x-6 gap-y-14 md:grid-cols-2 lg:grid-cols-3"}>{list.map((boat) => { const price = priceForDuration(boat, selection?.duration); const detailParams = new URLSearchParams(); if (selection?.guests) detailParams.set("guests", String(selection.guests)); if (selection?.duration) detailParams.set("duration", String(selection.duration)); if (selection?.date) detailParams.set("date", selection.date); const href = `/${lang}/fleet/${boat.slug}${detailParams.size ? `?${detailParams}` : ""}`; return <article key={boat.slug} className={horizontal ? "w-[85vw] max-w-[440px] shrink-0 snap-start md:w-[42vw]" : ""}><Link to={href} className="group block"><div className="relative aspect-[4/3] overflow-hidden rounded-md bg-muted"><ResponsiveImage image={boat.images[0]} alt={`${boat.name} private charter from ${boat.location.name[lang]}`} sizes={horizontal ? "(max-width:768px) 85vw, 42vw" : "(max-width:768px) 100vw, (max-width:1024px) 50vw, 33vw"} className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-[1.04]" /><span className="absolute left-4 top-4 flex items-center gap-1.5 rounded-full bg-sea px-3 py-2 text-[10px] font-semibold uppercase tracking-[0.1em] text-foam shadow-brand"><MapPin className="size-3" />{boat.location.shortName[lang]}</span><span className="absolute bottom-4 right-4 grid size-11 place-items-center rounded-md bg-foam/90 text-ink shadow-brand backdrop-blur transition-colors group-hover:bg-brass"><ArrowUpRight className="size-4" /></span></div></Link><div className="min-w-0 border-b border-border py-5"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0"><p className="section-kicker mb-1">{boat.type[lang]}</p><h3 className="font-display text-3xl font-medium leading-tight">{boat.name}</h3></div><p className="max-w-28 shrink-0 text-right font-display text-lg leading-tight md:max-w-none md:text-xl">{boat.priceOnRequest ? copy.priceOnRequest : price ? money(price, lang) : copy.priceOnRequest}</p></div>{selection?.duration && !boat.priceOnRequest && <p className="mt-1 text-right text-[10px] uppercase tracking-[.12em] text-muted-foreground">{t.forDuration} {selection.duration} h{selection.guests && price ? ` · ${money(Math.ceil(price / selection.guests), lang)} ${t.person}` : ""}</p>}<div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Users className="size-3.5"/>{boat.capacity}</span>{boat.length && <span className="flex items-center gap-1.5"><Ruler className="size-3.5"/>{boat.length}</span>}{boat.includes.slice(0,3).map((item) => <span key={item.en} className="flex items-center gap-1.5"><Check className="size-3 text-brass-ink"/>{item[lang]}</span>)}</div><Button asChild className="mt-6 w-full"><Link to={href}>{t.book}<ArrowUpRight/></Link></Button></div></article>; })}</div>;
  return <>{cards}{horizontal && <div className="mt-2 flex items-center justify-center gap-3 md:hidden"><span className="text-[10px] font-semibold uppercase tracking-[.14em] text-muted-foreground">{t.swipe}</span><span className="flex gap-1" aria-hidden="true">{list.map((boat, index) => <i key={boat.slug} className={`block size-1.5 rounded-full ${index === 0 ? "bg-brass-ink" : "bg-border"}`} />)}</span></div>}</>;
}
