import { Helmet } from "react-helmet-async";
import { SITE_URL, type Lang } from "@/data/siteData";

const labels: Record<Lang, Record<string, { title: string; description: string }>> = {
  en: { home: { title: "Banús Charters | Yacht Charter Marbella", description: "Private yacht charters in Puerto Banús, Marbella. Hand-picked boats, licensed captains and personal booking support." }, fleet: { title: "Yacht & Boat Fleet | Banús Charters", description: "Compare private yacht charter and boat rental options in Puerto Banús with clear prices by duration." }, experiences: { title: "Yacht Experiences Marbella | Banús Charters", description: "Sunset cruises, celebrations, family days, corporate charters and Jet Ski experiences in Marbella." }, faq: { title: "Yacht Charter FAQ | Banús Charters", description: "Answers about charter inclusions, fuel, weather, payments, children and meeting points in Puerto Banús." }, about: { title: "About Banús Charters | Puerto Banús", description: "Meet the local Puerto Banús charter brokerage team that personally selects every boat." }, contact: { title: "Contact Banús Charters | Puerto Banús", description: "Ask about yacht availability and plan your private charter in Puerto Banús, Marbella." }, legal: { title: "Legal Notice | Banús Charters", description: "Legal information and intermediary role of Banús Charters." }, privacy: { title: "Privacy Policy | Banús Charters", description: "How Banús Charters processes and protects personal data." }, cookies: { title: "Cookie Policy | Banús Charters", description: "Information about essential and optional cookies on Banús Charters." }, terms: { title: "Booking Terms | Banús Charters", description: "Terms for charter brokerage and bookings with Banús Charters." } },
  es: { home: { title: "Banús Charters | Alquiler barco Marbella", description: "Charters privados en Puerto Banús, Marbella. Barcos seleccionados, capitanes autorizados y gestión personal." }, fleet: { title: "Flota de barcos y yates | Banús Charters", description: "Compara alquiler de barcos y yates privados en Puerto Banús con precios claros por duración." }, experiences: { title: "Experiencias en barco Marbella | Banús Charters", description: "Puestas de sol, celebraciones, días en familia, eventos y Jet Ski en Marbella." }, faq: { title: "Preguntas sobre charters | Banús Charters", description: "Respuestas sobre incluidos, combustible, clima, pagos, niños y punto de encuentro en Puerto Banús." }, about: { title: "Sobre Banús Charters | Puerto Banús", description: "Conoce al equipo broker local de Puerto Banús que selecciona personalmente cada barco." }, contact: { title: "Contacto Banús Charters | Puerto Banús", description: "Consulta disponibilidad y organiza tu charter privado en Puerto Banús, Marbella." }, legal: { title: "Aviso legal | Banús Charters", description: "Información legal y función de intermediación de Banús Charters." }, privacy: { title: "Política de privacidad | Banús Charters", description: "Cómo Banús Charters trata y protege los datos personales." }, cookies: { title: "Política de cookies | Banús Charters", description: "Información sobre cookies esenciales y opcionales en Banús Charters." }, terms: { title: "Condiciones de reserva | Banús Charters", description: "Condiciones de intermediación y reservas de Banús Charters." } },
  fr: { home: { title: "Banús Charters | Location bateau Marbella", description: "Charters privés à Puerto Banús, Marbella. Bateaux sélectionnés, capitaines agréés et accompagnement personnalisé." }, fleet: { title: "Flotte de yachts et bateaux | Banús Charters", description: "Comparez les yachts et bateaux privés à Puerto Banús avec des prix clairs par durée." }, experiences: { title: "Expériences en yacht Marbella | Banús Charters", description: "Couchers de soleil, fêtes, journées famille, événements et Jet Ski à Marbella." }, faq: { title: "FAQ location bateau | Banús Charters", description: "Réponses sur les inclusions, le carburant, la météo, le paiement, les enfants et Puerto Banús." }, about: { title: "À propos de Banús Charters | Puerto Banús", description: "Découvrez l'équipe locale de courtage qui sélectionne personnellement chaque bateau." }, contact: { title: "Contacter Banús Charters | Puerto Banús", description: "Demandez les disponibilités et organisez votre charter privé à Puerto Banús, Marbella." }, legal: { title: "Mentions légales | Banús Charters", description: "Informations légales et rôle d'intermédiaire de Banús Charters." }, privacy: { title: "Politique de confidentialité | Banús Charters", description: "Traitement et protection des données personnelles par Banús Charters." }, cookies: { title: "Politique des cookies | Banús Charters", description: "Informations sur les cookies essentiels et optionnels de Banús Charters." }, terms: { title: "Conditions de réservation | Banús Charters", description: "Conditions de courtage et de réservation de Banús Charters." } },
};

export default function Seo({ lang, page = "home", title, description, path = "", jsonLd }: { lang: Lang; page?: string; title?: string; description?: string; path?: string; jsonLd?: object | object[] }) {
  const meta = labels[lang][page] ?? labels[lang].home;
  const url = `${SITE_URL}/${lang}${path}`;
  return <Helmet htmlAttributes={{ lang }}><title>{title ?? meta.title}</title><meta name="description" content={description ?? meta.description} /><link rel="canonical" href={url} /><link rel="alternate" hrefLang="en" href={`${SITE_URL}/en${path}`} /><link rel="alternate" hrefLang="es" href={`${SITE_URL}/es${path}`} /><link rel="alternate" hrefLang="fr" href={`${SITE_URL}/fr${path}`} /><link rel="alternate" hrefLang="x-default" href={`${SITE_URL}/en${path}`} /><meta property="og:title" content={title ?? meta.title} /><meta property="og:description" content={description ?? meta.description} /><meta property="og:url" content={url} /><meta property="og:type" content="website" /><meta property="og:image" content={`${SITE_URL}/banus-charters-social.jpg`} /><meta property="og:image:alt" content="Banús Charters private yacht in Puerto Banús" /><meta name="twitter:card" content="summary_large_image" /><meta name="twitter:title" content={title ?? meta.title} /><meta name="twitter:description" content={description ?? meta.description} /><meta name="twitter:image" content={`${SITE_URL}/banus-charters-social.jpg`} />{jsonLd && <script type="application/ld+json">{JSON.stringify(jsonLd)}</script>}</Helmet>;
}